### ISSUE TITLE
Convert definition cannot override default?

### ISSUE THREAD

**Issue by Epigene** [malt03/rails-rspec-file-toggle#1]
Hi, I want to opt out of putting controller specs into `spec/requests/`, and instead keep them in `specs/controllers/` (I'm of the mind that isolated specs for a source file must be located in an exactly matching spec file, but that's beside the point).

For example, I have an `app/controllers/application_controller.rb` file, and I expect a spec file for it to be at `spec/controllers/application_controller_spec.rb`

Unfortunately this exension keeps putting it in `spec/requests/application_spec.rb`

I tried these two settings.

```
"railsRspecFileToggle.convertDefinition": [
    {
      "app_directory": "controllers",
      "spec_directory": "controllers",
      "app_suffix": "",
      "spec_suffix": ""
    }
  ]
```

```
"railsRspecFileToggle.convertDefinition": [
    {
      "app_directory": "controllers",
      "spec_directory": "controllers",
      "app_suffix": "_controller",
      "spec_suffix": "_controller"
    }
  ]
```

**Comment by malt03** [comment]
Thanks for reporting the problem.
I checked and both of the settings you wrote seemed to work fine in my environment.
Please note that you need to restart Visual Studio Code to reflect the settings.

The versions of the various dependencies were out of date, so I updated them.
Updating the extension to 0.0.3 may help.

I will close this issue, but if you still encounter the problem, please write here.

**Comment by Epigene** [comment]
Kudos for checking it so soon! Can confirm that restarting VSC picks the config up and works as expected.
